name: Build APK

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: |
          yarn install

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build APK debug
        run: |
          cd android && ./gradlew assembleDebug

      - name: Build APK release
        run: |
          cd android && ./gradlew assembleRelease

      - name: Upload APK debug
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload APK release
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk